### ISSUE TITLE
Adding new octicons

### ISSUE THREAD

**Issue by gggfreak2003** [software-opal/octicons#1]
Thanks for this really nice library!

Could you please describe how I could add the missing octicons from version 8.4.1. I have found the data.json file in the repo but I dont know how to add the new icons.

Thanks for your help!

**Comment by software-opal** [comment]
Hey, thank you for your kind words. The short answer is that the `data.json` file comes from one of the built packages that they provide. I probably used the [JavaScript version](https://www.npmjs.com/package/octicons).

A better solution would be me spending a few hours writing a quick script to update that; and using GitHub Actions to somehow automate it.

**Comment by software-opal** [comment]
I've updated the `data.json` to Octicons 8.4.2; and I've also created a [script](https://github.com/software-opal/octicons/blob/master/update_data_json.sh) to automate that.

I've released 1.4.2 on PyPI and hopefully the versioning will somewhat follow Octicons; at least in the minor and patch parts.

I'm going to close the issue; but feel free to let me know how you go ✨

**Comment by gggfreak2003** [comment]
Very good work and thanks for the fast implementation! :-)
